### ISSUE TITLE
Custom DLL 

### ISSUE THREAD

**Issue by 0v3rfl00w** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#14]
Is it possible to use a pre-generated custom DLL ???
if  yes please explain to me how to do that with metasploit  
thanks .

**Comment by NickGoodLuck** [comment]
msfvenom   to a pre-generated custom DLL  and put it in ~/driver_c, remember change the dll's name,good luck!

**Comment by 0v3rfl00w** [comment]
Thanks nick .
