### ISSUE TITLE
Deps ? 

### ISSUE THREAD

**Issue by c0mrad** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#2]
What ?

![image](https://cloud.githubusercontent.com/assets/22458893/25392064/fbfbf28a-29d7-11e7-85eb-2a642ed1d05a.png)

**Comment by c0mrad** [comment]
I have the deps and i specified the path correctly and stell no such file ?

**Comment by UnaPibaGeek** [comment]
Mmm you miss "Doublepulsar-1.3.1.Skeleton.xml" in "deps" folder. Try download all again.

**Comment by c0mrad** [comment]
Yeah i messed something up while fidgeting with the ruby script haha
