### ISSUE TITLE
Guys , have a problem with installing winetricks

### ISSUE THREAD

**Issue by milannefosters** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#92]
I know that this is problem with the version of wine , but when im installing wine32 i have a same problem i just dont know how to fix it , im a newbee at Linux so i just dont know what to do 
help me pls xD )

milan@root:~$ sudo apt-get install winetricks -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package winetricks is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'winetricks' has no installation candidate
milan@root:~$ 

There is a "but is referred to by another package" but i tried the all things

**Comment by milannefosters** [comment]
Okay , i fixed it

**Comment by Bishtman12** [comment]
Hey! Can you please explain How did you fixed it?
