### ISSUE TITLE
make it support more windows platforms and support msf5

### ISSUE THREAD

**Issue by FinchZ** [ElevenPaths/Eternalblue-Doublepulsar-Metasploit#96]
1. change the file name to support msf5,or it won't be loaded successfully.
2. please modify the double_pulsar.exe to support "Windows Embedded Standard" .

**Comment by AtharavRH** [comment]
i am having alot trouble in loading that module on msf5 and kali 2019.3........i would be very much thankfull to anyone who can give me a solution.
 my error :
[-] No results from search
[-] Failed to load module: eternalblue_doublepulsar


thanks thanks thanks alot in advance.

**Comment by AtharavRH** [comment]
>     1. change the file name to support msf5,or it won't be loaded successfully.
> 
>     2. please modify the double_pulsar.exe to support "Windows Embedded Standard" .



>     1. change the file name to support msf5,or it won't be loaded successfully.
> 
>     2. please modify the double_pulsar.exe to support "Windows Embedded Standard" .

hey finch can you please elaborate ,what do u mean by changing file name to support msf5

**Comment by FinchZ** [comment]
> > ```
> > 1. change the file name to support msf5,or it won't be loaded successfully.
> > 
> > 2. please modify the double_pulsar.exe to support "Windows Embedded Standard" .
> > ```
> 
> > ```
> > 1. change the file name to support msf5,or it won't be loaded successfully.
> > 
> > 2. please modify the double_pulsar.exe to support "Windows Embedded Standard" .
> > ```
> 
> hey finch can you please elaborate ,what do u mean by changing file name to support msf5

yes,you can rename the file,just do not include "-" such as "eternal.rb"

**Comment by AtharavRH** [comment]
It is saved in that format already still doesn't works.

**Comment by AtharavRH** [comment]
It's is stored in that msf5 executable format!
Will you please tell what all changes we need to make?
